import { Bill } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { RichTextDisplay } from "src/components/RichTextDisplay";

import { api } from "src/utils/api";

const Home: NextPage = () => {
  const billsQuery = api.bills.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <ul className="w-full max-w-xl">
          {billsQuery.data?.map((b) => (
            <li key={b.id} className="my-4">
              <Bill bill={b} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;

function Bill({ bill }: { bill: Bill }) {
  return (
    <div className="flex w-full flex-col rounded-xl bg-white p-4">
      <span className="text-xl font-bold">{bill.title}</span>
      <span className="text-sm text-gray-500">
        {new Date(bill.published * 1000).toLocaleString()}
      </span>
      <div className="py-4">
        <RichTextDisplay html={bill.description} />
      </div>
    </div>
  );
}
