import { Bill } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { RichTextDisplay } from "src/components/RichTextDisplay";

import { api } from "src/utils/api";

const Home: NextPage = () => {
  const billsQuery = api.bills.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-4">
        <ul className="w-full max-w-xl">
          {billsQuery.data?.map((b) => (
            <li key={b.id} className="my-4">
              <Bill bill={b} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;

function Bill({
  bill,
}: {
  bill: Bill & { likes: unknown[]; dislikes: unknown[] };
}) {
  const [likes, setLikes] = useState(bill.likes.length);
  const [dislikes, setDislikes] = useState(bill.dislikes.length);
  const likeMutation = api.bills.like.useMutation();
  const dislikeMutation = api.bills.dislike.useMutation();

  return (
    <div className="flex w-full flex-col rounded-xl bg-white p-4">
      <span className="text-xl font-bold">{bill.title}</span>
      <span className="text-sm text-gray-500">
        {new Date(bill.published * 1000).toLocaleString()}
      </span>
      <div className="py-4">
        <RichTextDisplay html={bill.description} />
      </div>
      <div className="flex w-full flex-row items-center justify-center">
        <div className="flex flex-col items-center">
          <span>{dislikes}</span>
          <button
            className="rounded-lg bg-red-600 p-2 px-4 text-white"
            onClick={() => {
              setDislikes((d) => d + 1);
              dislikeMutation.mutate({ billId: bill.id });
            }}
          >
            Dislike
          </button>
        </div>
        <div className="p-2"></div>
        <div className="flex flex-col items-center">
          <span>{likes}</span>
          <button
            className="rounded-lg bg-blue-600 p-2 px-4 text-white"
            onClick={() => {
              setLikes((d) => d + 1);
              likeMutation.mutate({ billId: bill.id });
            }}
          >
            Like
          </button>
        </div>
      </div>
    </div>
  );
}
